export const metadata = {
  title: 'Homepage',
  description: 'Generated by Next.js',
}
import "../styles/homepage.css";


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
